/* AIN'T NEVER GONNA FORGET PRESIDENTS NOW — president data (v2)
   n      = number (1..47; Cleveland is 22 AND 24, Trump is 45 AND 47)
   name   = full name
   short  = last name (quiz labels)
   start, end = term years
   party  = political party
   nick   = historical nickname (shown on detail card)
   fact   = ONE kid-friendly fun fact, illustrated by `prop`
   recipe = pixel-portrait build options (see pixelart.js)
   prop   = key into PixelArt.PROPS
*/
window.PRESIDENTS = [
  { n:1,  name:"George Washington", short:"Washington", start:1789, end:1797, party:"None", nick:"The Father of His Country",
    fact:"His false teeth were NOT wood — they were ivory, gold, and even other people's teeth!",
    recipe:{skin:"light", hair:"wig", hairColor:"#ececec", brows:"flat", mouth:"smile", collar:"cravat"}, prop:"teeth" },
  { n:2,  name:"John Adams", short:"J. Adams", start:1797, end:1801, party:"Federalist", nick:"The Atlas of Independence",
    fact:"He was the very first president to live in the White House.",
    recipe:{skin:"light", hair:"balding", hairColor:"#d8d8d8", brows:"arch", mouth:"flat", collar:"cravat"}, prop:"house" },
  { n:3,  name:"Thomas Jefferson", short:"Jefferson", start:1801, end:1809, party:"Dem.-Rep.", nick:"The Sage of Monticello",
    fact:"He wrote the Declaration of Independence with a quill pen.",
    recipe:{skin:"light", hair:"wave", hairColor:"#b0703c", brows:"flat", mouth:"smile", collar:"cravat"}, prop:"scroll" },
  { n:4,  name:"James Madison", short:"Madison", start:1809, end:1817, party:"Dem.-Rep.", nick:"The Father of the Constitution",
    fact:"He was our SHORTEST president — just 5 feet 4 inches tall!",
    recipe:{skin:"light", hair:"wig", hairColor:"#e6e6e6", brows:"flat", mouth:"flat", collar:"cravat"}, prop:"ruler" },
  { n:5,  name:"James Monroe", short:"Monroe", start:1817, end:1825, party:"Dem.-Rep.", nick:"The Last Cocked Hat",
    fact:"Monrovia, the capital of the country Liberia in Africa, is named after him.",
    recipe:{skin:"light", hair:"side", hairColor:"#9a8a6a", brows:"flat", mouth:"smile", collar:"cravat"}, prop:"globe" },
  { n:6,  name:"John Quincy Adams", short:"J.Q. Adams", start:1825, end:1829, party:"Dem.-Rep.", nick:"Old Man Eloquent",
    fact:"He liked to go skinny-dipping in the Potomac River every morning!",
    recipe:{skin:"light", hair:"balding", hairColor:"#b9b9b9", brows:"thick", mouth:"flat", collar:"cravat"}, prop:"water" },
  { n:7,  name:"Andrew Jackson", short:"Jackson", start:1829, end:1837, party:"Democratic", nick:"Old Hickory",
    fact:"He had a pet parrot that learned to swear and had to be removed from his funeral!",
    recipe:{skin:"light", hair:"long", hairColor:"#cfcfcf", brows:"thick", mouth:"flat", collar:"stock"}, prop:"parrot" },
  { n:8,  name:"Martin Van Buren", short:"Van Buren", start:1837, end:1841, party:"Democratic", nick:"Old Kinderhook",
    fact:"His campaign clubs helped make the word 'OK' famous — from his nickname 'Old Kinderhook'!",
    recipe:{skin:"light", hair:"balding", hairColor:"#d8d8d8", facial:"mutton", brows:"thick", mouth:"smile", collar:"stock"}, prop:"ok" },
  { n:9,  name:"William Henry Harrison", short:"W.H. Harrison", start:1841, end:1841, party:"Whig", nick:"Old Tippecanoe",
    fact:"He gave a super-long speech in freezing weather and served the SHORTEST term — 31 days.",
    recipe:{skin:"light", hair:"side", hairColor:"#c8c8c8", brows:"flat", mouth:"flat", collar:"stock"}, prop:"snow" },
  { n:10, name:"John Tyler", short:"Tyler", start:1841, end:1845, party:"Whig", nick:"His Accidency",
    fact:"He had 15 children — more than any other president!",
    recipe:{skin:"light", hair:"wave", hairColor:"#7a5230", brows:"arch", mouth:"flat", collar:"stock"}, prop:"family" },
  { n:11, name:"James K. Polk", short:"Polk", start:1845, end:1849, party:"Democratic", nick:"Young Hickory",
    fact:"He made a to-do list of big goals, finished them ALL, and retired after one term.",
    recipe:{skin:"light", hair:"long", hairColor:"#8a8a92", brows:"flat", mouth:"flat", collar:"stock"}, prop:"list" },
  { n:12, name:"Zachary Taylor", short:"Taylor", start:1849, end:1850, party:"Whig", nick:"Old Rough and Ready",
    fact:"His war horse 'Old Whitey' grazed on the White House lawn.",
    recipe:{skin:"tan", hair:"short", hairColor:"#9a9a9a", brows:"thick", mouth:"flat", collar:"stock"}, prop:"horse" },
  { n:13, name:"Millard Fillmore", short:"Fillmore", start:1850, end:1853, party:"Whig", nick:"The Last of the Whigs",
    fact:"He started the first permanent White House library.",
    recipe:{skin:"light", hair:"side", hairColor:"#d0d0d0", brows:"flat", mouth:"smile", collar:"bowtie", tie:"#1a1a1a"}, prop:"book" },
  { n:14, name:"Franklin Pierce", short:"Pierce", start:1853, end:1857, party:"Democratic", nick:"Handsome Frank",
    fact:"He memorized his entire 3,000-word inauguration speech and gave it with NO notes.",
    recipe:{skin:"light", hair:"wave", hairColor:"#4a3626", brows:"arch", mouth:"smile", collar:"stock"}, prop:"speech" },
  { n:15, name:"James Buchanan", short:"Buchanan", start:1857, end:1861, party:"Democratic", nick:"Old Buck",
    fact:"He's the only president who never married — no First Lady!",
    recipe:{skin:"light", hair:"quiff", hairColor:"#e2e2e2", brows:"flat", mouth:"flat", collar:"bowtie", tie:"#1a1a1a"}, prop:"noring" },
  { n:16, name:"Abraham Lincoln", short:"Lincoln", start:1861, end:1865, party:"Republican", nick:"Honest Abe",
    fact:"He stored letters and notes inside his tall stovepipe top hat!",
    recipe:{skin:"light", hair:"short", hairColor:"#2b2b2b", facial:"chinbeard", brows:"flat", mouth:"flat", hat:"tophat", collar:"suit", tie:"#1a1a1a"}, prop:"tophat" },
  { n:17, name:"Andrew Johnson", short:"A. Johnson", start:1865, end:1869, party:"National Union", nick:"The Tennessee Tailor",
    fact:"He was a tailor and kept sewing his own suits, even as president.",
    recipe:{skin:"light", hair:"side", hairColor:"#3a3a3a", brows:"thick", mouth:"flat", collar:"suit", tie:"#b08a3c"}, prop:"needle" },
  { n:18, name:"Ulysses S. Grant", short:"Grant", start:1869, end:1877, party:"Republican", nick:"Unconditional Surrender",
    fact:"He got a $20 speeding ticket… for riding his horse too fast through Washington!",
    recipe:{skin:"light", hair:"short", hairColor:"#5a3a22", facial:"beard", brows:"flat", mouth:"flat", collar:"suit", tie:"#a03030"}, prop:"ticket" },
  { n:19, name:"Rutherford B. Hayes", short:"Hayes", start:1877, end:1881, party:"Republican", nick:"The Dark-Horse President",
    fact:"He had the first telephone installed in the White House — its number was '1'.",
    recipe:{skin:"light", hair:"short", hairColor:"#7a5a3a", facial:"beard", brows:"flat", mouth:"flat", collar:"suit", tie:"#a03030"}, prop:"phone" },
  { n:20, name:"James A. Garfield", short:"Garfield", start:1881, end:1881, party:"Republican", nick:"The Preacher President",
    fact:"It's said he could write Latin with one hand and Greek with the other AT THE SAME TIME.",
    recipe:{skin:"light", hair:"short", hairColor:"#5a3a22", facial:"beard", brows:"arch", mouth:"smile", collar:"suit", tie:"#a03030"}, prop:"pencils" },
  { n:21, name:"Chester A. Arthur", short:"Arthur", start:1881, end:1885, party:"Republican", nick:"Elegant Arthur",
    fact:"He was super fashionable and owned around 80 pairs of pants!",
    recipe:{skin:"light", hair:"short", hairColor:"#2b2b2b", facial:"mutton", brows:"flat", mouth:"flat", collar:"suit", tie:"#a03030"}, prop:"pants" },
  { n:22, name:"Grover Cleveland", short:"Cleveland", start:1885, end:1889, party:"Democratic", nick:"Uncle Jumbo",
    fact:"He got married INSIDE the White House — the only president ever to do that.",
    recipe:{skin:"light", hair:"balding", hairColor:"#4a3320", facial:"mustache", brows:"flat", mouth:"flat", collar:"suit", tie:"#3a6ea5"}, prop:"rings" },
  { n:23, name:"Benjamin Harrison", short:"B. Harrison", start:1889, end:1893, party:"Republican", nick:"The Human Iceberg",
    fact:"He got the White House's first electricity — but was too scared to touch the light switches!",
    recipe:{skin:"light", hair:"short", hairColor:"#cfcfcf", facial:"beard", brows:"flat", mouth:"flat", collar:"suit", tie:"#a03030"}, prop:"bulb" },
  { n:24, name:"Grover Cleveland", short:"Cleveland", start:1893, end:1897, party:"Democratic", nick:"Uncle Jumbo, Act II",
    fact:"He was the FIRST president to serve two separate terms — he's #22 AND #24!",
    recipe:{skin:"light", hair:"balding", hairColor:"#4a3320", facial:"mustache", brows:"flat", mouth:"flat", collar:"suit", tie:"#3a6ea5"}, prop:"twoterm" },
  { n:25, name:"William McKinley", short:"McKinley", start:1897, end:1901, party:"Republican", nick:"The Idol of Ohio",
    fact:"He wore a lucky red carnation flower on his jacket every single day.",
    recipe:{skin:"light", hair:"side", hairColor:"#3a3a3a", brows:"thick", mouth:"flat", collar:"suit", tie:"#a03030", accessory:"flower"}, prop:"flower" },
  { n:26, name:"Theodore Roosevelt", short:"T. Roosevelt", start:1901, end:1909, party:"Republican", nick:"The Rough Rider",
    fact:"The 'teddy bear' was named after him when he refused to shoot a bear on a hunting trip!",
    recipe:{skin:"light", hair:"short", hairColor:"#5a3a22", facial:"mustache", brows:"thick", mouth:"grin", glasses:"round", collar:"suit", tie:"#a03030"}, prop:"teddy" },
  { n:27, name:"William Howard Taft", short:"Taft", start:1909, end:1913, party:"Republican", nick:"Big Bill",
    fact:"Our biggest president — a famous story says he once got stuck in a White House bathtub!",
    recipe:{skin:"light", hair:"balding", hairColor:"#cfcfcf", facial:"handlebar", brows:"flat", mouth:"smile", collar:"suit", tie:"#a03030"}, prop:"bathtub" },
  { n:28, name:"Woodrow Wilson", short:"Wilson", start:1913, end:1921, party:"Democratic", nick:"The Schoolmaster",
    fact:"He kept a flock of SHEEP on the White House lawn to mow the grass during World War I.",
    recipe:{skin:"light", hair:"side", hairColor:"#9a9a9a", brows:"flat", mouth:"flat", glasses:"round", collar:"suit", tie:"#3a6ea5"}, prop:"sheep" },
  { n:29, name:"Warren G. Harding", short:"Harding", start:1921, end:1923, party:"Republican", nick:"The Front-Porch President",
    fact:"He once gambled away a whole set of White House china in a poker game!",
    recipe:{skin:"light", hair:"side", hairColor:"#c8c8c8", brows:"thick", mouth:"flat", collar:"suit", tie:"#a03030"}, prop:"cards" },
  { n:30, name:"Calvin Coolidge", short:"Coolidge", start:1923, end:1929, party:"Republican", nick:"Silent Cal",
    fact:"He had a pet raccoon named Rebecca that walked around the White House on a leash.",
    recipe:{skin:"light", hair:"side", hairColor:"#8a4b2a", brows:"flat", mouth:"flat", collar:"suit", tie:"#a03030"}, prop:"raccoon" },
  { n:31, name:"Herbert Hoover", short:"Hoover", start:1929, end:1933, party:"Republican", nick:"The Great Engineer",
    fact:"His son kept two pet ALLIGATORS that sometimes roamed the White House grounds.",
    recipe:{skin:"light", hair:"side", hairColor:"#b9b9b9", brows:"arch", mouth:"flat", collar:"suit", tie:"#a03030"}, prop:"gator" },
  { n:32, name:"Franklin D. Roosevelt", short:"F. Roosevelt", start:1933, end:1945, party:"Democratic", nick:"The New Dealer",
    fact:"He's the only president elected FOUR times — more than 12 years in office!",
    recipe:{skin:"light", hair:"balding", hairColor:"#9a9a9a", brows:"flat", mouth:"grin", glasses:"round", collar:"suit", tie:"#3a6ea5"}, prop:"x4" },
  { n:33, name:"Harry S. Truman", short:"Truman", start:1945, end:1953, party:"Democratic", nick:"Give 'Em Hell Harry",
    fact:"He kept a sign on his desk that said 'The Buck Stops Here.'",
    recipe:{skin:"light", hair:"side", hairColor:"#cfcfcf", brows:"flat", mouth:"smile", glasses:"round", collar:"suit", tie:"#3a6ea5"}, prop:"buck" },
  { n:34, name:"Dwight D. Eisenhower", short:"Eisenhower", start:1953, end:1961, party:"Republican", nick:"Ike",
    fact:"He loved golf so much he had a putting green built right outside the Oval Office.",
    recipe:{skin:"light", hair:"bald", hairColor:"#cfcfcf", brows:"flat", mouth:"grin", collar:"suit", tie:"#a03030"}, prop:"golf" },
  { n:35, name:"John F. Kennedy", short:"Kennedy", start:1961, end:1963, party:"Democratic", nick:"Jack",
    fact:"In WWII he carved a rescue message into a COCONUT shell to save his shipwrecked crew!",
    recipe:{skin:"tan", hair:"quiff", hairColor:"#6b4a2a", brows:"flat", mouth:"grin", collar:"suit", tie:"#3a6ea5"}, prop:"coconut" },
  { n:36, name:"Lyndon B. Johnson", short:"L. Johnson", start:1963, end:1969, party:"Democratic", nick:"LBJ",
    fact:"He owned a car that could drive straight into a lake — and loved pranking guests with it!",
    recipe:{skin:"tan", hair:"side", hairColor:"#9a9a9a", brows:"thick", mouth:"flat", collar:"suit", tie:"#3a6ea5"}, prop:"car" },
  { n:37, name:"Richard Nixon", short:"Nixon", start:1969, end:1974, party:"Republican", nick:"Tricky Dick",
    fact:"He had a one-lane bowling alley built under the White House.",
    recipe:{skin:"light", hair:"peak", hairColor:"#3a3a3a", facial:"shadow", brows:"thick", mouth:"flat", collar:"suit", tie:"#a03030"}, prop:"bowling" },
  { n:38, name:"Gerald Ford", short:"Ford", start:1974, end:1977, party:"Republican", nick:"Mr. Nice Guy",
    fact:"He was a college football star who turned down offers from two NFL teams.",
    recipe:{skin:"light", hair:"side", hairColor:"#caa15a", brows:"flat", mouth:"smile", collar:"suit", tie:"#a03030"}, prop:"football" },
  { n:39, name:"Jimmy Carter", short:"Carter", start:1977, end:1981, party:"Democratic", nick:"The Peanut Farmer",
    fact:"Before politics he was a PEANUT farmer in Georgia — and once reported a UFO sighting!",
    recipe:{skin:"light", hair:"side", hairColor:"#c8c8c8", brows:"flat", mouth:"grin", collar:"suit", tie:"#3a6ea5"}, prop:"peanut" },
  { n:40, name:"Ronald Reagan", short:"Reagan", start:1981, end:1989, party:"Republican", nick:"The Great Communicator",
    fact:"A Hollywood actor first, he kept a jar of jelly beans on his desk and on Air Force One.",
    recipe:{skin:"light", hair:"quiff", hairColor:"#4a3626", brows:"arch", mouth:"grin", collar:"suit", tie:"#a03030"}, prop:"jellybeans" },
  { n:41, name:"George H. W. Bush", short:"G.H.W. Bush", start:1989, end:1993, party:"Republican", nick:"Poppy",
    fact:"He HATED broccoli so much he banned it from Air Force One!",
    recipe:{skin:"light", hair:"side", hairColor:"#b9b9b9", brows:"flat", mouth:"smile", collar:"suit", tie:"#a03030"}, prop:"broccoli" },
  { n:42, name:"Bill Clinton", short:"Clinton", start:1993, end:2001, party:"Democratic", nick:"The Comeback Kid",
    fact:"He played the saxophone in sunglasses on late-night TV during his campaign.",
    recipe:{skin:"light", hair:"quiff", hairColor:"#cfcfcf", brows:"flat", mouth:"grin", collar:"suit", tie:"#3a6ea5"}, prop:"sax" },
  { n:43, name:"George W. Bush", short:"G.W. Bush", start:2001, end:2009, party:"Republican", nick:"Dubya",
    fact:"He once owned the Texas Rangers baseball team.",
    recipe:{skin:"tan", hair:"short", hairColor:"#8a8a8a", brows:"arch", mouth:"smirk", collar:"suit", tie:"#a03030"}, prop:"baseball" },
  { n:44, name:"Barack Obama", short:"Obama", start:2009, end:2017, party:"Democratic", nick:"No Drama Obama",
    fact:"He's a huge Spider-Man fan and collected comic books growing up.",
    recipe:{skin:"dark", hair:"short", hairColor:"#1a1a1a", brows:"flat", mouth:"grin", collar:"suit", tie:"#3a6ea5"}, prop:"comic" },
  { n:45, name:"Donald Trump", short:"Trump", start:2017, end:2021, party:"Republican", nick:"The Donald",
    fact:"He had a quick movie cameo in 'Home Alone 2' — pointing Kevin toward the hotel lobby.",
    recipe:{skin:"tan", hair:"comb", hairColor:"#d8b35a", brows:"thick", mouth:"flat", collar:"suit", tie:"#a03030"}, prop:"clapper" },
  { n:46, name:"Joe Biden", short:"Biden", start:2021, end:2025, party:"Democratic", nick:"Amtrak Joe",
    fact:"He's famous for loving ice cream — chocolate chip is his favorite!",
    recipe:{skin:"light", hair:"side", hairColor:"#e6e6e6", brows:"flat", mouth:"grin", glasses:"square", collar:"suit", tie:"#3a6ea5"}, prop:"icecream" },
  { n:47, name:"Donald Trump", short:"Trump", start:2025, end:2029, party:"Republican", nick:"The Donald, Act II",
    fact:"He became the SECOND president to serve two separate terms — the first since Grover Cleveland!",
    recipe:{skin:"tan", hair:"comb", hairColor:"#d8b35a", brows:"thick", mouth:"flat", collar:"suit", tie:"#a03030"}, prop:"star" }
];

/* Eras for the timeline (by president number) */
window.ERAS = [
  { name:"The Founding Era",             span:"1789–1829", from:1,  to:6  },
  { name:"Expansion & Division",         span:"1829–1861", from:7,  to:15 },
  { name:"Civil War & Reconstruction",   span:"1861–1877", from:16, to:18 },
  { name:"The Gilded Age",               span:"1877–1901", from:19, to:25 },
  { name:"Progressive Era & World Wars", span:"1901–1953", from:26, to:33 },
  { name:"The Cold War",                 span:"1953–1993", from:34, to:41 },
  { name:"The Modern Era",               span:"1993–today", from:42, to:47 }
];
