/* WES KNOW PREZ — president data
   Each entry:
   n      = number (1..46; Cleveland is 22 AND 24)
   name   = full name
   short  = last name (for quiz buttons)
   start, end = term years (end null = "present"-ish; here Biden 2025)
   party  = political party
   fact   = ONE kid-friendly fun fact, illustrated by `prop`
   recipe = pixel-portrait build options (see pixelart.js)
   prop   = key into PROPS (the pixel icon that illustrates the fact)
*/
window.PRESIDENTS = [
  { n:1,  name:"George Washington", short:"Washington", start:1789, end:1797, party:"None",
    fact:"His false teeth were NOT wood — they were ivory, gold and even other people's teeth!",
    recipe:{skin:"light", hair:"wig", hairColor:"#eeeeee", facial:"none", collar:"cravat"}, prop:"teeth" },
  { n:2,  name:"John Adams", short:"J. Adams", start:1797, end:1801, party:"Federalist",
    fact:"He was the very first president to live in the White House.",
    recipe:{skin:"light", hair:"wig", hairColor:"#e6e6e6", facial:"none", collar:"cravat"}, prop:"house" },
  { n:3,  name:"Thomas Jefferson", short:"Jefferson", start:1801, end:1809, party:"Dem.-Rep.",
    fact:"He wrote the Declaration of Independence with a quill pen.",
    recipe:{skin:"light", hair:"wig", hairColor:"#caa15a", facial:"none", collar:"cravat"}, prop:"scroll" },
  { n:4,  name:"James Madison", short:"Madison", start:1809, end:1817, party:"Dem.-Rep.",
    fact:"He was our SHORTEST president — just 5 feet 4 inches tall!",
    recipe:{skin:"light", hair:"wig", hairColor:"#e6e6e6", facial:"none", collar:"cravat"}, prop:"ruler" },
  { n:5,  name:"James Monroe", short:"Monroe", start:1817, end:1825, party:"Dem.-Rep.",
    fact:"His Monroe Doctrine told Europe to stay out of the Americas.",
    recipe:{skin:"light", hair:"wig", hairColor:"#e6e6e6", facial:"none", collar:"cravat"}, prop:"globe" },
  { n:6,  name:"John Quincy Adams", short:"J.Q. Adams", start:1825, end:1829, party:"Dem.-Rep.",
    fact:"He liked to go skinny-dipping in the Potomac River every morning!",
    recipe:{skin:"light", hair:"side", hairColor:"#b9b9b9", facial:"none", collar:"cravat"}, prop:"water" },
  { n:7,  name:"Andrew Jackson", short:"Jackson", start:1829, end:1837, party:"Democratic",
    fact:"He had a pet parrot that learned to swear and had to leave his funeral!",
    recipe:{skin:"light", hair:"long", hairColor:"#cccccc", facial:"none", collar:"cravat"}, prop:"parrot" },
  { n:8,  name:"Martin Van Buren", short:"Van Buren", start:1837, end:1841, party:"Democratic",
    fact:"His nickname 'Old Kinderhook' is where we get the word 'OK'!",
    recipe:{skin:"light", hair:"side", hairColor:"#d8d8d8", facial:"mutton", collar:"suit"}, prop:"ok" },
  { n:9,  name:"William Henry Harrison", short:"W.H. Harrison", start:1841, end:1841, party:"Whig",
    fact:"He gave a super-long speech in the cold and had the SHORTEST term — 31 days.",
    recipe:{skin:"light", hair:"short", hairColor:"#c8c8c8", facial:"none", collar:"suit"}, prop:"snow" },
  { n:10, name:"John Tyler", short:"Tyler", start:1841, end:1845, party:"Whig",
    fact:"He had 15 children — more than any other president!",
    recipe:{skin:"light", hair:"wave", hairColor:"#7a5230", facial:"none", collar:"suit"}, prop:"family" },
  { n:11, name:"James K. Polk", short:"Polk", start:1845, end:1849, party:"Democratic",
    fact:"He made a to-do list of goals, finished them ALL, then retired in one term.",
    recipe:{skin:"light", hair:"long", hairColor:"#4a3320", facial:"none", collar:"suit"}, prop:"list" },
  { n:12, name:"Zachary Taylor", short:"Taylor", start:1849, end:1850, party:"Whig",
    fact:"His war horse 'Old Whitey' grazed on the White House lawn.",
    recipe:{skin:"tan", hair:"short", hairColor:"#9a9a9a", facial:"none", collar:"suit"}, prop:"horse" },
  { n:13, name:"Millard Fillmore", short:"Fillmore", start:1850, end:1853, party:"Whig",
    fact:"He created the first permanent White House library.",
    recipe:{skin:"light", hair:"side", hairColor:"#e0e0e0", facial:"none", collar:"suit"}, prop:"book" },
  { n:14, name:"Franklin Pierce", short:"Pierce", start:1853, end:1857, party:"Democratic",
    fact:"He memorized his entire inauguration speech and gave it with NO notes.",
    recipe:{skin:"light", hair:"wave", hairColor:"#6b4a2a", facial:"none", collar:"suit"}, prop:"speech" },
  { n:15, name:"James Buchanan", short:"Buchanan", start:1857, end:1861, party:"Democratic",
    fact:"He's the only president who never married — no First Lady!",
    recipe:{skin:"light", hair:"side", hairColor:"#e0e0e0", facial:"none", collar:"suit"}, prop:"noring" },
  { n:16, name:"Abraham Lincoln", short:"Lincoln", start:1861, end:1865, party:"Republican",
    fact:"He stored letters and notes inside his tall stovepipe top hat!",
    recipe:{skin:"light", hair:"short", hairColor:"#2b2b2b", facial:"chinbeard", hat:"tophat", collar:"suit"}, prop:"tophat" },
  { n:17, name:"Andrew Johnson", short:"A. Johnson", start:1865, end:1869, party:"National Union",
    fact:"He was a tailor and sewed his own suits, even as president.",
    recipe:{skin:"light", hair:"side", hairColor:"#3a3a3a", facial:"none", collar:"suit"}, prop:"needle" },
  { n:18, name:"Ulysses S. Grant", short:"Grant", start:1869, end:1877, party:"Republican",
    fact:"He once got a speeding ticket… for riding his horse too fast in the city!",
    recipe:{skin:"light", hair:"short", hairColor:"#5a3a22", facial:"beard", collar:"suit"}, prop:"ticket" },
  { n:19, name:"Rutherford B. Hayes", short:"Hayes", start:1877, end:1881, party:"Republican",
    fact:"He had the first telephone installed in the White House.",
    recipe:{skin:"light", hair:"short", hairColor:"#6b4a2a", facial:"beard", collar:"suit"}, prop:"phone" },
  { n:20, name:"James A. Garfield", short:"Garfield", start:1881, end:1881, party:"Republican",
    fact:"He could write Latin with one hand and Greek with the other AT THE SAME TIME.",
    recipe:{skin:"light", hair:"short", hairColor:"#5a3a22", facial:"beard", collar:"suit"}, prop:"pencils" },
  { n:21, name:"Chester A. Arthur", short:"Arthur", start:1881, end:1885, party:"Republican",
    fact:"He was super fashionable and owned around 80 pairs of pants!",
    recipe:{skin:"light", hair:"short", hairColor:"#2b2b2b", facial:"mutton", collar:"suit"}, prop:"pants" },
  { n:22, name:"Grover Cleveland", short:"Cleveland", start:1885, end:1889, party:"Democratic",
    fact:"He got married INSIDE the White House — the only president to do so.",
    recipe:{skin:"light", hair:"balding", hairColor:"#4a3320", facial:"mustache", collar:"suit"}, prop:"rings" },
  { n:23, name:"Benjamin Harrison", short:"B. Harrison", start:1889, end:1893, party:"Republican",
    fact:"He got the first electricity — but was scared to touch the light switches!",
    recipe:{skin:"light", hair:"short", hairColor:"#cfcfcf", facial:"beard", collar:"suit"}, prop:"bulb" },
  { n:24, name:"Grover Cleveland", short:"Cleveland", start:1893, end:1897, party:"Democratic",
    fact:"He's the ONLY president to serve two separate terms — #22 AND #24!",
    recipe:{skin:"light", hair:"balding", hairColor:"#4a3320", facial:"mustache", collar:"suit"}, prop:"twoterm" },
  { n:25, name:"William McKinley", short:"McKinley", start:1897, end:1901, party:"Republican",
    fact:"He wore a lucky red carnation flower on his jacket every day.",
    recipe:{skin:"light", hair:"side", hairColor:"#3a3a3a", facial:"none", collar:"suit"}, prop:"flower" },
  { n:26, name:"Theodore Roosevelt", short:"T. Roosevelt", start:1901, end:1909, party:"Republican",
    fact:"The 'teddy bear' was named after him after he spared a bear on a hunt!",
    recipe:{skin:"light", hair:"short", hairColor:"#5a3a22", facial:"mustache", glasses:"round", collar:"suit"}, prop:"teddy" },
  { n:27, name:"William Howard Taft", short:"Taft", start:1909, end:1913, party:"Republican",
    fact:"He was our biggest president — a story says he once got stuck in a bathtub!",
    recipe:{skin:"light", hair:"balding", hairColor:"#cfcfcf", facial:"handlebar", collar:"suit"}, prop:"bathtub" },
  { n:28, name:"Woodrow Wilson", short:"Wilson", start:1913, end:1921, party:"Democratic",
    fact:"He kept a flock of SHEEP on the White House lawn to mow the grass.",
    recipe:{skin:"light", hair:"side", hairColor:"#9a9a9a", facial:"none", glasses:"round", collar:"suit"}, prop:"sheep" },
  { n:29, name:"Warren G. Harding", short:"Harding", start:1921, end:1923, party:"Republican",
    fact:"He once gambled away a set of White House china in a poker game!",
    recipe:{skin:"light", hair:"side", hairColor:"#c8c8c8", facial:"none", collar:"suit"}, prop:"cards" },
  { n:30, name:"Calvin Coolidge", short:"Coolidge", start:1923, end:1929, party:"Republican",
    fact:"He had a pet raccoon named Rebecca that lived in the White House.",
    recipe:{skin:"light", hair:"side", hairColor:"#8a4b2a", facial:"none", collar:"suit"}, prop:"raccoon" },
  { n:31, name:"Herbert Hoover", short:"Hoover", start:1929, end:1933, party:"Republican",
    fact:"His sons kept two pet ALLIGATORS that roamed the White House grounds.",
    recipe:{skin:"light", hair:"side", hairColor:"#b9b9b9", facial:"none", collar:"suit"}, prop:"gator" },
  { n:32, name:"Franklin D. Roosevelt", short:"F. Roosevelt", start:1933, end:1945, party:"Democratic",
    fact:"He's the only president elected FOUR times — 12 years in office!",
    recipe:{skin:"light", hair:"balding", hairColor:"#9a9a9a", facial:"none", glasses:"round", collar:"suit"}, prop:"x4" },
  { n:33, name:"Harry S. Truman", short:"Truman", start:1945, end:1953, party:"Democratic",
    fact:"He kept a sign on his desk that said 'The Buck Stops Here.'",
    recipe:{skin:"light", hair:"side", hairColor:"#cfcfcf", facial:"none", glasses:"square", collar:"suit"}, prop:"buck" },
  { n:34, name:"Dwight D. Eisenhower", short:"Eisenhower", start:1953, end:1961, party:"Republican",
    fact:"He loved golf so much he had a putting green built at the White House.",
    recipe:{skin:"light", hair:"bald", hairColor:"#cfcfcf", facial:"none", collar:"suit"}, prop:"golf" },
  { n:35, name:"John F. Kennedy", short:"Kennedy", start:1961, end:1963, party:"Democratic",
    fact:"In WWII he carved a rescue message into a COCONUT to save his crew!",
    recipe:{skin:"tan", hair:"quiff", hairColor:"#6b4a2a", facial:"none", collar:"suit"}, prop:"coconut" },
  { n:36, name:"Lyndon B. Johnson", short:"L. Johnson", start:1963, end:1969, party:"Democratic",
    fact:"He had a car that could drive into a lake — and pranked guests with it!",
    recipe:{skin:"tan", hair:"side", hairColor:"#9a9a9a", facial:"none", collar:"suit"}, prop:"car" },
  { n:37, name:"Richard Nixon", short:"Nixon", start:1969, end:1974, party:"Republican",
    fact:"He had a bowling alley built in the White House basement.",
    recipe:{skin:"light", hair:"side", hairColor:"#3a3a3a", facial:"shadow", collar:"suit"}, prop:"bowling" },
  { n:38, name:"Gerald Ford", short:"Ford", start:1974, end:1977, party:"Republican",
    fact:"He was a football star who turned down two pro NFL team offers.",
    recipe:{skin:"light", hair:"side", hairColor:"#caa15a", facial:"none", collar:"suit"}, prop:"football" },
  { n:39, name:"Jimmy Carter", short:"Carter", start:1977, end:1981, party:"Democratic",
    fact:"Before politics he was a PEANUT farmer in Georgia.",
    recipe:{skin:"light", hair:"side", hairColor:"#c8c8c8", facial:"none", collar:"suit"}, prop:"peanut" },
  { n:40, name:"Ronald Reagan", short:"Reagan", start:1981, end:1989, party:"Republican",
    fact:"A Hollywood actor first, he kept a jar of jelly beans on his desk.",
    recipe:{skin:"light", hair:"quiff", hairColor:"#5a3a22", facial:"none", collar:"suit"}, prop:"jellybeans" },
  { n:41, name:"George H. W. Bush", short:"G.H.W. Bush", start:1989, end:1993, party:"Republican",
    fact:"He HATED broccoli and banned it from Air Force One!",
    recipe:{skin:"light", hair:"side", hairColor:"#b9b9b9", facial:"none", glasses:"square", collar:"suit"}, prop:"broccoli" },
  { n:42, name:"Bill Clinton", short:"Clinton", start:1993, end:2001, party:"Democratic",
    fact:"He played the saxophone on TV during his campaign.",
    recipe:{skin:"light", hair:"quiff", hairColor:"#cfcfcf", facial:"none", collar:"suit"}, prop:"sax" },
  { n:43, name:"George W. Bush", short:"G.W. Bush", start:2001, end:2009, party:"Republican",
    fact:"He once owned the Texas Rangers baseball team.",
    recipe:{skin:"tan", hair:"short", hairColor:"#8a8a8a", facial:"none", collar:"suit"}, prop:"baseball" },
  { n:44, name:"Barack Obama", short:"Obama", start:2009, end:2017, party:"Democratic",
    fact:"He's a huge Spider-Man fan and collects comic books.",
    recipe:{skin:"dark", hair:"short", hairColor:"#1a1a1a", facial:"none", collar:"suit"}, prop:"comic" },
  { n:45, name:"Donald Trump", short:"Trump", start:2017, end:2021, party:"Republican",
    fact:"He had a quick movie cameo in the film 'Home Alone 2'.",
    recipe:{skin:"tan", hair:"comb", hairColor:"#d8b35a", facial:"none", collar:"suit"}, prop:"clapper" },
  { n:46, name:"Joe Biden", short:"Biden", start:2021, end:2025, party:"Democratic",
    fact:"He's famous for loving ice cream — it's his favorite treat!",
    recipe:{skin:"light", hair:"side", hairColor:"#e6e6e6", facial:"none", glasses:"square", collar:"suit"}, prop:"icecream" },
  { n:47, name:"Donald Trump", short:"Trump", start:2025, end:2029, party:"Republican",
    fact:"Like Grover Cleveland, he served two separate terms — he's both #45 AND #47!",
    recipe:{skin:"tan", hair:"comb", hairColor:"#d8b35a", facial:"none", collar:"suit"}, prop:"star" }
];
